name: pnyws
description: Penny wise
version: 0.1.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  injector: ^1.0.8
  shared_preferences: ^0.5.8
  get_version: ^0.2.2
  intl: ^0.16.1
  flutter_scale_aware:
    git: https://github.com/jogboms/flutter_scale_aware.git
  rxdart: ^0.24.1
  uuid: ^2.2.0
  flutter_slidable: ^0.5.5
  cloud_firestore: ^0.14.0-dev.1
  firebase_auth: ^0.17.0-dev.1
  google_sign_in: ^4.5.1
  memoize: ^2.0.0
  faker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mfsao: ^0.1.3
  mockito: ^4.1.1

dependency_overrides:
  firebase_core: ^0.5.0-dev.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
